spring.application.name=notification-service
server.port=8087

spring.kafka.bootstrap-servers=localhost:9092

# spring.kafka.consumer.group-id=notification-service-v2
# spring.kafka.consumer.auto-offset-reset=latest

# Mailtrap
spring.mail.host=sandbox.smtp.mailtrap.io
spring.mail.port=587
spring.mail.username=6aa3b38fd56a5b
spring.mail.password=23e0af3c5022ed

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.auto-offset-reset=latest
spring.kafka.consumer.group-id=notification-service-v3

spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8181/realms/appverse





keycloak.token-uri=http://localhost:8181/realms/appverse/protocol/openid-connect/token
# Keycloak Admin Client Configuration for user-service
appverse.keycloak.server-url=http://localhost:8181
appverse.keycloak.realm=appverse
appverse.keycloak.client-id=notification-service
appverse.keycloak.client-secret=z4KKnWqMsEKjLdo9rFR2ZZcoVmGUD8EL