spring.application.name=notification-service

server.port=8087

spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8181/realms/appverse

appverse.keycloak.server-url=http://localhost:8181
appverse.keycloak.realm=appverse
appverse.keycloak.client-id=user-service-admin
appverse.keycloak.client-secret=qqqMNamMcycaJbkIl3HAJOurboNVdnNG

spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.consumer.group-id=notification-service-group

spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer
# ==========================================
# EMAIL (JavaMailSender) CONFIGURATION
# ==========================================
# Replace with your actual SMTP server details and credentials

# --- Example for Gmail ---
spring.mail.host=sandbox.smtp.mailtrap.io
spring.mail.port=587
spring.mail.username=6aa3b38fd56a5b
spring.mail.password=23e0af3c5022ed

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

spring.kafka.consumer.properties.spring.json.type.mapping=event:com.appverse.notification_service.event.Event

management.endpoints.web.exposure.include=health, info, metrics, prometheus
management.metrics.distribution.percentiles-histogram.http.server.requests=true
management.observations.key-values.application=notification-service

management.tracing.sampling.probability=1.0
