spring.application.name=notification-service
server.port=8087

spring.kafka.bootstrap-servers=localhost:9092

# Mailtrap
spring.mail.host=sandbox.smtp.mailtrap.io
spring.mail.port=587
spring.mail.username=6aa3b38fd56a5b
spring.mail.password=23e0af3c5022ed

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
