spring.application.name=identity-service
server.port=8085

# ===== JWT validation (VERY IMPORTANT) =====
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8181/realms/appverse

# ===== Keycloak Admin Client =====
keycloak.serverUrl=http://localhost:8181
keycloak.realm=appverse
keycloak.clientId=identity-service-client
keycloak.clientSecret=3CJju5d0m5gh3kuT8rjOuKN3ouLPnEoW

