spring.application.name=api-gateway
server.port=9000

# Existing Resource Server config
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8181/realms/appverse

app.cors.allowed-origins=http://localhost:4200,http://localhost:3000


spring.security.oauth2.client.registration.developer-client.client-id=developer-client
spring.security.oauth2.client.registration.developer-client.client-secret=XYTXY2QLm8y5QrZNvQMxTj6lq7nuHHiM
spring.security.oauth2.client.registration.developer-client.authorization-grant-type=authorization_code
spring.security.oauth2.client.registration.developer-client.redirect-uri={baseUrl}/login/oauth2/code/developer-client
spring.security.oauth2.client.registration.developer-client.scope=openid,profile,email,roles

spring.security.oauth2.client.registration.user-client.client-id=user-client
spring.security.oauth2.client.registration.user-client.client-secret=36i7DhedFiqLOPjthUAvK8j6Xyj8IMr3
spring.security.oauth2.client.registration.user-client.authorization-grant-type=authorization_code
spring.security.oauth2.client.registration.user-client.redirect-uri={baseUrl}/login/oauth2/code/user-client
spring.security.oauth2.client.registration.user-client.scope=openid,profile,email,roles



# Identity provider info (same realm for both clients)
spring.security.oauth2.client.provider.keycloak.issuer-uri=http://localhost:8181/realms/appverse
spring.security.oauth2.client.provider.keycloak.user-name-attribute=preferred_username


spring.security.oauth2.client.registration.developer-client.provider=keycloak
spring.security.oauth2.client.registration.user-client.provider=keycloak



springdoc.swagger-ui.path=/swagger-ui.html

springdoc.swagger-ui.urls[0].name=Application Service
springdoc.swagger-ui.urls[0].url=/aggregate/application-service/v3/api-docs
springdoc.swagger-ui.urls[1].name=Developer Service
springdoc.swagger-ui.urls[1].url=/aggregate/developer-service/v3/api-docs
springdoc.swagger-ui.urls[2].name=User Service
springdoc.swagger-ui.urls[2].url=/aggregate/user-service/v3/api-docs
springdoc.swagger-ui.urls[3].name=Cart Service
springdoc.swagger-ui.urls[3].url=/aggregate/cart-service/v3/api-docs
springdoc.swagger-ui.urls[4].name=Order Service
springdoc.swagger-ui.urls[4].url=/aggregate/order-service/v3/api-docs
springdoc.swagger-ui.urls[5].name=Payment Service
springdoc.swagger-ui.urls[5].url=/aggregate/payment-service/v3/api-docs
springdoc.swagger-ui.urls[6].name=Subscription Service
springdoc.swagger-ui.urls[6].url=/aggregate/subscription-service/v3/api-docs


management.endpoints.web.exposure.include=health,info,prometheus,metrics,circuitbreakers
management.endpoint.health.show-details=always
management.health.circuitbreakers.enabled=true


resilience4j.circuitbreaker.configs.default.registerHealthIndicator=true
resilience4j.circuitbreaker.configs.default.slidingWindowType=COUNT_BASED
resilience4j.circuitbreaker.configs.default.slidingWindowSize=10
resilience4j.circuitbreaker.configs.default.minimumNumberOfCalls=5
resilience4j.circuitbreaker.configs.default.failureRateThreshold=50
resilience4j.circuitbreaker.configs.default.waitDurationInOpenState=30s
resilience4j.circuitbreaker.configs.default.permittedNumberOfCallsInHalfOpenState=3
resilience4j.circuitbreaker.configs.default.automaticTransitionFromOpenToHalfOpenEnabled=true

resilience4j.timelimiter.configs.default.timeout-duration=4s
resilience4j.timelimiter.configs.default.cancel-running-future=true

resilience4j.retry.configs.default.max-attempts=3
resilience4j.retry.configs.default.wait-duration=100ms
resilience4j.retry.configs.default.enable-exponential-backoff=true
resilience4j.retry.configs.default.exponential-backoff-multiplier=2
resilience4j.circuitbreaker.instances.developerServiceCB.baseConfig=default

resilience4j.circuitbreaker.instances.applicationServiceCB.baseConfig=default

resilience4j.circuitbreaker.instances.userServiceCB.baseConfig=default
resilience4j.circuitbreaker.instances.cartServiceCB.baseConfig=default
resilience4j.circuitbreaker.instances.orderServiceCB.baseConfig=default
resilience4j.circuitbreaker.instances.paymentServiceCB.baseConfig=default
resilience4j.circuitbreaker.instances.subscriptionServiceCB.baseConfig=default


spring.cloud.gateway.mvc.circuitbreaker.enabled=true

spring.cloud.gateway.httpclient.connect-timeout=3000
spring.cloud.gateway.httpclient.response-timeout=4s

keycloak.token-uri=http://localhost:8181/realms/appverse/protocol/openid-connect/token

appverse.keycloak.server-url=http://localhost:8181
appverse.keycloak.realm=appverse
appverse.keycloak.client-id=api-gateway
appverse.keycloak.client-secret=fqwIJ8YWUDyrgQDScK7k666ERs887HVy