spring.application.name=order-service
spring.datasource.url=jdbc:mysql://localhost:3310/order_service
spring.datasource.username=root
spring.datasource.password=ankur
spring.jpa.hibernate.ddl-auto=none
server.port=8084
spring.jpa.show-sql=true

spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8181/realms/appverse





springdoc.swagger-ui.path=/swagger-ui.html

keycloak.token-uri=http://localhost:8181/realms/appverse/protocol/openid-connect/token

appverse.keycloak.server-url=http://localhost:8181
appverse.keycloak.realm=appverse
appverse.keycloak.client-id=order-service
appverse.keycloak.client-secret=npGRQtQd9cqcWLMMd2rVifxCZ0WlwtUB



resilience4j.circuitbreaker.instances.appServiceClient.register-health-indicator=true
resilience4j.circuitbreaker.instances.appServiceClient.failure-rate-threshold=50
resilience4j.circuitbreaker.instances.appServiceClient.sliding-window-size=10
resilience4j.circuitbreaker.instances.appServiceClient.minimum-number-of-calls=5

resilience4j.retry.instances.appServiceClient.max-attempts=3
resilience4j.retry.instances.appServiceClient.wait-duration=500ms
# Choose one of the following ways to specify what to retry on:
# Option 1: List specific exceptions
resilience4j.retry.instances.appServiceClient.retry-exceptions= \
  java.io.IOException, \
  java.util.concurrent.TimeoutException, \
  feign.RetryableException


management.endpoints.web.exposure.include=*

logging.level.io.github.resilience4j=DEBUG
logging.level.org.springframework.cloud.circuitbreaker=DEBUG

spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer

# management.endpoints.web.exposure.include=health, info, metrics, prometheus
management.metrics.distribution.percentiles-histogram.http.server.requests=true
management.tracing.sampling.probability=1.0

management.observations.key-values.application=${spring.application.name}