spring.application.name=developer-service
spring.datasource.url=jdbc:mysql://localhost:3307/developer_service
spring.datasource.username=root
spring.datasource.password=ankur
spring.jpa.hibernate.ddl-auto=none
server.port=8081
spring.jpa.show-sql=true



services.identity-service.url=http://localhost:8085

springdoc.swagger-ui.path=/swagger-ui.html

spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer

# logging.level.com.appverse.developer_service=DEBUG
# logging.level.org.springframework.web=DEBUG
# logging.level.org.springframework.security=DEBUG
server.error.include-stacktrace=never
server.error.include-exception=false
server.error.include-message=never

 management.endpoints.web.exposure.include=health, info, prometheus
# management.metrics.distribution.percentiles-histogram.http.server.requests=true
# management.observations.key-values.application=developer-service

management.tracing.sampling.probability=1.0


# logging.level.root=INFO
# logging.level.com.appverse=DEBUG
# logging.level.org.springframework.web=DEBUG
# logging.level.org.springframework.security=DEBUG
# logging.level.org.hibernate.SQL=DEBUG
# logging.level.org.hibernate.type.descriptor.sql=TRACE
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8181/realms/appverse


keycloak.token-uri=http://localhost:8181/realms/appverse/protocol/openid-connect/token
# appverse.keycloak.server-url=http://localhost:8181
appverse.keycloak.realm=appverse
appverse.keycloak.client-id=developer-service
appverse.keycloak.client-secret=K8XyMbWSY89DhcsZmmWlz9mtXAdKRA8i



# ---- Silence observability noise ----
logging.level.org.springframework.web.client.RestTemplate=INFO
logging.level.org.springframework.security=INFO
logging.level.org.springframework.security.web.FilterChainProxy=INFO
logging.level.org.springframework.security.web.authentication=INFO

logging.level.org.springframework.boot.actuate=INFO
logging.level.org.springframework.boot.actuate.endpoint.web=INFO

logging.level.io.micrometer=INFO
logging.level.zipkin2=INFO
logging.level.brave=INFO
