spring.application.name=cart-service
spring.datasource.url=jdbc:mysql://localhost:3309/cart_service
spring.datasource.username=root
spring.datasource.password=ankur
spring.jpa.hibernate.ddl-auto=none
server.port=8083
spring.jpa.show-sql=true

spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8181/realms/appverse



spring.main.web-application-type=servlet
appverse.application-service.url=http://localhost:8080
springdoc.swagger-ui.path=/swagger-ui.html


resilience4j.circuitbreaker.instances.applicationServiceClient.register-health-indicator=true
resilience4j.circuitbreaker.instances.applicationServiceClient.failure-rate-threshold=50
resilience4j.circuitbreaker.instances.applicationServiceClient.sliding-window-size=10
resilience4j.circuitbreaker.instances.applicationServiceClient.minimum-number-of-calls=5

# resilience4j.circuitbreaker.instances.subscriptionServiceClient.register-health-indicator=true
# resilience4j.circuitbreaker.instances.subscriptionServiceClient.failure-rate-threshold=50
# resilience4j.circuitbreaker.instances.subscriptionServiceClient.sliding-window-size=10
# resilience4j.circuitbreaker.instances.subscriptionServiceClient.minimum-number-of-calls=5

# management.endpoints.web.exposure.include=*

logging.level.io.github.resilience4j=DEBUG
logging.level.org.springframework.cloud.circuitbreaker=DEBUG

spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer

management.endpoints.web.exposure.include=health, info, metrics, prometheus
management.metrics.distribution.percentiles-histogram.http.server.requests=true
# management.observations.key-values.application=cart-service

management.tracing.sampling.probability=1.0

management.observations.key-values.application=${spring.application.name}

keycloak.token-uri=http://localhost:8181/realms/appverse/protocol/openid-connect/token

appverse.keycloak.server-url=http://localhost:8181
appverse.keycloak.realm=appverse
appverse.keycloak.client-id=cart-service
appverse.keycloak.client-secret=oz3RRr0LLy5qV6ktnRV00nueAD0zk13t