// === In developer-service Project ===
package com.appverse.developer_service.event.payload;

import com.appverse.developer_service.enums.DeveloperType; // Assuming you have this enum
import java.time.Instant; // If your Developer entity uses Instant for timestamps

public record DeveloperProfileCreatedPayload(
    String developerId, // The ID generated by your system (e.g., UUID string)
    String keycloakUserId,
    String name,
    String email,
    DeveloperType developerType,
    String companyName, // Optional
    Instant createdAt   // Assuming your Developer entity has this
) {}